export { default as Home} from './home'
export { default as Reports } from './reports'
export { default as FormReport } from './formReport'
export { default as Profile } from './profile'
export { default as List } from './list'
export { default as Location } from './TESTlocation'
export { default as ActivityIndicator } from './activityIndicator'
export { default as TextInput } from './textInput'