export { default as Home} from './home'
export { default as Reports } from './screens/reports'
export { default as FormReport } from './screens/FormReport'
export { default as Profile } from './profile'
export { default as List } from './list'
export { default as Location } from './screens/TESTlocation'
export { default as Map } from './screens/map'
export { default as SpecificReport } from './screens/report'
